"""Detached, lease-bound verifier worker. Never calls a model or edits a workspace."""
from __future__ import annotations

import os
import hashlib
from functools import lru_cache
from pathlib import Path
import platform
import shutil
import signal
import subprocess
import sys
import threading
import time
import uuid

from harness.measurement_v5 import MeasurementEngine, decode
from harness.common import canonical_bytes, canonical_hash, redact
from .errors import HarnessError, require
from .snapshots import validate_candidate
from .store import Store, identifier
from . import semantics, acceptance, evidence


def clean_environment() -> dict:
    # No provider credentials, Python module search overrides or application plugins.
    keys = ("PATH", "Path", "PATHEXT", "SystemRoot", "WINDIR", "TEMP", "TMP", "LANG", "LC_ALL", "BUN")
    return {key: os.environ[key] for key in keys if key in os.environ}


def spawn_worker(state_dir: Path, job_id: str) -> int:
    source = str(Path(__file__).resolve().parents[1])
    code = f"import sys; sys.path.insert(0, {source!r}); from harness_external.worker import main; main()"
    options = {"start_new_session": True} if os.name != "nt" else {"creationflags": subprocess.CREATE_NEW_PROCESS_GROUP}
    child = subprocess.Popen([sys.executable, "-I", "-c", code, str(state_dir), job_id], cwd=source,
                             stdin=subprocess.DEVNULL, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
                             env=clean_environment(), **options)
    return child.pid


def stop_child(child: subprocess.Popen) -> None:
    if os.name == "nt":
        if child.poll() is None:
            try:
                subprocess.run(["taskkill", "/PID", str(child.pid), "/T", "/F"], capture_output=True, timeout=5)
            except (OSError, subprocess.TimeoutExpired):
                child.kill()
    else:
        try:
            os.killpg(child.pid, signal.SIGTERM)
        except ProcessLookupError:
            pass
    try:
        child.wait(timeout=3)
    except subprocess.TimeoutExpired:
        if os.name == "nt":
            child.kill()
        else:
            try:
                os.killpg(child.pid, signal.SIGKILL)
            except ProcessLookupError:
                pass
        child.wait(timeout=3)


def file_fingerprint(info):
    return info.st_dev, info.st_ino, info.st_size, info.st_mtime_ns, info.st_ctime_ns


@lru_cache(maxsize=64)
def runtime_digest(filename, fingerprint):
    # Recheck inode/ctime/mtime on every use, but avoid reading a large Bun binary
    # four times per paired command. This is still local consistency, not an
    # adversarial same-user tamper barrier or a transitive dependency digest.
    path = Path(filename)
    require(file_fingerprint(path.stat()) == fingerprint, "RUNTIME_CHANGED", "Runtime changed before hashing")
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        while data := stream.read(1024 * 1024):
            digest.update(data)
    require(file_fingerprint(path.stat()) == fingerprint, "RUNTIME_CHANGED", "Runtime changed during hashing")
    return digest.hexdigest()


def runtime_identity(check):
    """Identify top-level runtime binaries; not their entire dependency graph."""
    binaries = {"adapter": shutil.which(os.environ.get("BUN", "bun")),
                "verifier_python": sys.executable,
                "command": shutil.which(check["argv"][0], path="/usr/local/bin:/usr/bin:/bin")
                           if "/" not in check["argv"][0] or Path(check["argv"][0]).is_absolute() else None}
    result = {}
    for name, filename in binaries.items():
        if filename is None:
            result[name] = {"status": "unresolved_or_candidate_local"}
            continue
        path = Path(filename).resolve()
        before = path.stat()
        require(before.st_size <= 256 * 1024 * 1024, "RUNTIME_IDENTITY_LIMIT", "Runtime executable exceeds identity bound")
        digest = runtime_digest(str(path), file_fingerprint(before))
        after = path.stat()
        require(file_fingerprint(before) == file_fingerprint(after),
                "RUNTIME_CHANGED", "Runtime executable changed while identifying it")
        result[name] = {"path": str(path), "sha256": digest}
    return result


def execute_sandbox(check: dict, payload: Path, state_dir: Path, abort: threading.Event, remaining: float) -> dict:
    """Return only a receipt generated by our adapter, never one supplied by a caller."""
    started = time.time()
    bridge = Path(__file__).resolve().parents[2] / "runtime" / "script" / "external-harness-sandbox.ts"
    bun = shutil.which(os.environ.get("BUN", "bun"))
    if not bridge.is_file() or not bun:
        return {"status": "not_run", "reason": "SANDBOX_ADAPTER_UNAVAILABLE: source checkout and Bun are required for command checks"}
    require(not abort.is_set() and remaining > 0, "VERIFICATION_CANCELLED", "Verification was cancelled")
    request = {"workspace": str(payload), "argv": check["argv"], "cwd": check["cwd"],
               "timeoutMs": max(1, min(int(remaining * 1000), check["timeout_seconds"] * 1000))}
    environment = clean_environment()
    environment["XDG_STATE_HOME"] = str(state_dir / "sandbox-state")
    options = {"start_new_session": True} if os.name != "nt" else {"creationflags": subprocess.CREATE_NEW_PROCESS_GROUP}
    child = subprocess.Popen([bun, "run", str(bridge)], cwd=bridge.parent,
                             stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE,
                             env=environment, **options)
    try:
        first = True
        # The existing sandbox adapter caps process streams; this outer deadline
        # bounds setup, cleanup, and a stuck adapter as well.
        while True:
            if abort.is_set() or time.time() - started > remaining:
                stop_child(child)
                raise HarnessError("VERIFICATION_CANCELLED", "Verification cancelled or job deadline expired")
            try:
                output, errors = child.communicate(canonical_bytes(request) if first else None, timeout=0.2)
                break
            except subprocess.TimeoutExpired:
                first = False
        require(len(output) <= 1024 * 1024 and child.returncode == 0, "SANDBOX_ADAPTER_ERROR", "Sandbox adapter failed or exceeded protocol bounds")
        value = decode(output.decode("utf-8"))
        require(isinstance(value, dict) and value.get("status") in {"completed", "not_run", "error"}, "SANDBOX_PROTOCOL", "Invalid sandbox adapter response")
        return value
    finally:
        if child.poll() is None:
            stop_child(child)
        for stream in (child.stdin, child.stdout, child.stderr):
            if stream:
                stream.close()


def execute_job(state_dir: str | Path, job_id: str) -> None:
    from .service import verifier_identity
    store = Store(state_dir)
    owner = uuid.uuid4().hex
    abort, done = threading.Event(), threading.Event()
    with store.transaction() as connection:
        job = store.job(connection, job_id)
        run = store.run(connection, job["run_id"])
        if job["status"] != "queued" or run["active_job"] != job_id or run["status"] != "active":
            return
        job.update(status="running", heartbeat_at=time.time(), owner=owner, pid=os.getpid(), cleanup="running")
        store.save_job(connection, job)
        run["verification"] = {"status": "running", "job_id": job_id}
        store.save_run(connection, run)

    def heartbeat():
        while not done.wait(1):
            try:
                with store.transaction() as connection:
                    current = store.job(connection, job_id)
                    active = store.current(connection, job["run_id"])
                    if current["status"] != "running" or current.get("owner") != owner or active["status"] != "active" or active["active_job"] != job_id or time.time() >= job["deadline_at"]:
                        abort.set()
                        return
                    current["heartbeat_at"] = time.time()
                    store.save_job(connection, current)
            except Exception:
                abort.set()
                return

    monitor = threading.Thread(target=heartbeat, daemon=True)
    monitor.start()
    result = None
    failure = None
    reports = []
    case_reports = []
    case_items = []
    check_items = []
    comparisons = []
    measured_scope = []
    environment = {}
    try:
        require(time.time() < job["deadline_at"], "DEADLINE_EXCEEDED", "Job expired before execution")
        require(run["contract"]["verifier"] == verifier_identity(), "VERIFIER_CHANGED", "Pinned verifier implementation changed")
        require(job.get("check_set_hash") == semantics.check_set_hash(job["checks"]), "CHECK_SET_CHANGED", "Pinned check set changed")
        if run.get("acceptance"):
            acceptance.validate(run["acceptance"], store.directory(run["run_id"]))
            require(job.get("acceptance_binding_hash") == run["acceptance"]["binding_hash"],
                    "ACCEPTANCE_BINDING_CORRUPT", "Job has a different acceptance policy")
        def envelope(kind, request_id, body):
            return {"version": 5, "id": request_id, "runId": run["run_id"], "scopeId": job_id, "type": kind, "payload": body}
        subjects = ([("baseline", job["baseline"])] if job.get("baseline") else []) + [("candidate", job["candidate"])]
        tasks = [(role, subject, check) for role, subject in subjects for check in job["checks"]]
        last_subject = None
        for index, (subject_role, candidate, check_record) in enumerate(tasks):
            payload = store.directory(run["run_id"]) / identifier(candidate["candidate_id"], "candidate") / "payload"
            if last_subject != candidate["candidate_id"]:
                validate_candidate(candidate, payload)
                if run.get("acceptance"):
                    acceptance.validate_subject(run["acceptance"], candidate)
                engine = MeasurementEngine()
                engine.handle(envelope("run.open", "open-" + job_id + "-" + subject_role, {"snapshotRoot": str(payload)}))
                last_subject = candidate["candidate_id"]
            environment = {"python": platform.python_version(), "platform": platform.platform(),
                           "verifier": verifier_identity()["implementation_hash"], "assurance": "local-advisory"}
            require(environment["verifier"] == run["contract"]["verifier"]["implementation_hash"],
                    "VERIFIER_CHANGED", "Verifier implementation changed during measurements")
            spec = dict(check_record["spec"])
            check = dict(spec["parameters"])
            require(not abort.is_set() and time.time() < job["deadline_at"], "VERIFICATION_CANCELLED", "Worker no longer owns the verification")
            validate_candidate(candidate, payload)
            measurement = {"subject": candidate["subject"], "manifestJson": canonical_bytes(candidate["manifest"]).decode(),
                           "environmentHash": canonical_hash(environment)}
            provenance = None
            case_summary = None
            if check["kind"] == "command":
                check["timeout_seconds"] = max(1, spec["timeoutMs"] // 1000)
                environment["top_level_runtime"] = runtime_identity(check)
                if check.get("adapter"):
                    from .adapter_execution import execute as execute_adapter
                    binding = job["adapter_bindings"][check_record["check_id"]]
                    environment["adapter_identity"] = binding
                    def checkpoint_case(case, adapter_identity):
                        identity = {"job": job_id, "subject": candidate["subject"], "check": check_record["ref"], "case": case["case_id"]}
                        item = {"record_type": "case-observation-v1", "observation_id": "case:" + canonical_hash(identity),
                                "run_id": run["run_id"], "job_id": job_id, "attempt": run["verification_attempts"],
                                "check_id": check_record["check_id"], "check_ref": check_record["ref"], "subject": candidate["subject"],
                                "candidate_hash": candidate["candidate_hash"], "contract_hash": job["contract_hash"],
                                "check_set_hash": job["check_set_hash"], "interpretation_ref": job["interpretation_ref"],
                                "policy_ref": job["policy_ref"], "subject_role": subject_role, "adapter_identity": adapter_identity,
                                "domain_identity": job["domain_identity"],
                                "acceptance_binding_hash": job.get("acceptance_binding_hash"), "runtime_environment_hash": canonical_hash(environment),
                                "execution_observation_id": "observation:" + job_id + ":" + str(index),
                                "origin": "verifier", "trust": "locally_reported", "case": {**case, "phases": redact(case["phases"])}}
                        item["record_hash"] = canonical_hash(item)
                        with store.transaction() as connection:
                            store.checkpoint_case(connection, job_id, owner, item)
                        case_reports.append({"observation_id": item["observation_id"], "record_hash": item["record_hash"]})
                        case_items.append(item)
                    capture, case_summary = execute_adapter(check, payload, store.root, abort, job["deadline_at"] - time.time(), binding, checkpoint_case)
                else:
                    environment.pop("adapter_identity", None)
                    capture = execute_sandbox(check, payload, store.root, abort, job["deadline_at"] - time.time())
                require(environment["top_level_runtime"] == runtime_identity(check), "RUNTIME_CHANGED", "Runtime executable changed during command execution")
                measured_runtime = capture.get("provenance") or {}
                environment["sandbox"] = {key: measured_runtime[key] for key in ("backend", "containment", "network", "kernel", "distro") if key in measured_runtime}
                parameters = {"kind": "command", "argv": check["argv"], "cwd": check["cwd"], "expectedExitCode": 0}
                if capture["status"] in {"completed", "error"} and capture.get("capture"):
                    receipt = capture["capture"]
                    require(receipt["argv"] == check["argv"] and receipt["cwd"] == check["cwd"], "RECEIPT_BINDING", "Command receipt identity mismatch")
                    measurement["capture"] = {**receipt, "stdout": redact(receipt["stdout"]), "stderr": redact(receipt["stderr"])}
                    provenance = capture.get("provenance")
                else:
                    provenance = capture
                capabilities, timeout = ["execute"], check["timeout_seconds"] * 1000
            else:
                parameters, capabilities, timeout = check, ["read"], 1000
            spec = {**spec, "parameters": parameters, "ref": check_record["ref"]}
            require(run["contract"]["verifier"] == verifier_identity(), "VERIFIER_CHANGED", "Verifier changed during execution")
            measurement["environmentHash"] = canonical_hash(environment)
            measurement["check"] = spec
            report = engine.handle(envelope("measure", job_id + ":" + str(index), measurement))
            if case_summary is not None:
                from .observation_rules import evaluate
                report["result"].setdefault("findings", []).extend(evaluate(case_summary, check["adapter"]["rules"]))
                if not case_summary["collection_complete"] or not case_summary["session_complete"] or case_summary.get("protocol_error"):
                    report["result"]["execution"] = "error"
                    report["result"].setdefault("error", {"code": case_summary.get("protocol_error") or "CASE_SESSION_INCOMPLETE", "message": "Case discovery or execution did not finish completely"})
            validate_candidate(candidate, payload)
            item = {"check_index": index, "observation": redact(report), "sandbox": provenance}
            checkpoint = {"observation_id": report["observationId"], "run_id": run["run_id"], "job_id": job_id,
                          "attempt": run["verification_attempts"], "check_id": check_record["check_id"], "check_ref": check_record["ref"],
                          "subject": candidate["subject"], "candidate_hash": candidate["candidate_hash"], "contract_hash": job["contract_hash"],
                          "interpretation_ref": job["interpretation_ref"], "policy_ref": job["policy_ref"],
                          "check_set_hash": job["check_set_hash"], "domain_identity": job["domain_identity"],
                          "comparison_status": semantics.comparison_status(report), "origin": "verifier", "trust": "locally_measured",
                          "report": item}
            checkpoint.update(measurement_kind=check["kind"], execution_status=evidence.execution_status(report, provenance),
                              role=check_record.get("role", "mandatory" if check_record["check_id"] in run["gate_bindings"] else "exploratory"),
                              acceptance_binding_hash=job.get("acceptance_binding_hash"), subject_role=subject_role)
            if case_summary is not None:
                from collections import Counter
                checkpoint["case_summary"] = {key: value for key, value in case_summary.items() if key != "cases"}
                checkpoint["case_summary"].update(discovered_count=len(case_summary["cases"]),
                        selected_count=sum(c["selected"] is True for c in case_summary["cases"]),
                        executed_count=sum(c["executed"] for c in case_summary["cases"]),
                        outcomes=dict(Counter(c["outcome"] for c in case_summary["cases"])))
                checkpoint["case_observation_refs"] = [ref for ref, item in zip(case_reports, case_items)
                        if item["check_ref"] == check_record["ref"] and item["subject"] == candidate["subject"]]
            checkpoint["record_hash"] = canonical_hash(checkpoint)
            with store.transaction() as connection:
                store.checkpoint(connection, job_id, owner, checkpoint)
            reports.append({"observation_id": checkpoint["observation_id"], "record_hash": checkpoint["record_hash"]})
            check_items.append(checkpoint)
            if subject_role == "candidate":
                comparisons.append(checkpoint["comparison_status"])
            measured_scope.append({"observation_id": checkpoint["observation_id"], "check_id": checkpoint["check_id"],
                                   "kind": check["kind"], "role": checkpoint["role"],
                                   "subject_role": subject_role, "environment_hash": canonical_hash(environment),
                                   "execution_status": checkpoint["execution_status"], "comparison_status": checkpoint["comparison_status"],
                                   "case_summary": checkpoint.get("case_summary")})
        validate_candidate(candidate, payload)
        status = "passed" if all(s == "passed" for s in comparisons) else "failed"
        if "incomplete" in comparisons:
            status = "incomplete"
        result = {"status": status, "candidate_hash": job["candidate_hash"], "contract_hash": job["contract_hash"],
                  "schema_version": "verification-result-v2", "check_set_hash": job["check_set_hash"],
                  "domain_identity": job["domain_identity"], "environment": environment, "observation_refs": reports,
                  "measurement_scope": evidence.scope([s for s in measured_scope if s["subject_role"] == "candidate"]),
                  "baseline_comparison": evidence.compare(measured_scope, job, run),
                  "acceptance_binding_hash": job.get("acceptance_binding_hash"), "finished_at": time.time()}
        from .develop_cases import requirement_report
        result.update(case_observation_refs=case_reports,
                      requirement_observations=requirement_report(run["contract"], check_items, case_items))
        if result["requirement_observations"] is not None:
            result["requirement_observations"]["scope"] = {"run_id": run["run_id"], "job_id": job_id, "candidate_hash": job["candidate_hash"],
                        "check_set_hash": job["check_set_hash"], "contract_hash": job["contract_hash"], "acceptance_binding_hash": job.get("acceptance_binding_hash")}
        result["result_hash"] = canonical_hash(result)
    except Exception as error:
        failure = {"code": getattr(error, "code", "VERIFICATION_ERROR"), "message": str(redact(str(error)))[:2000]}
        if reports:
            result = {"status": "incomplete", "candidate_hash": job["candidate_hash"], "contract_hash": job["contract_hash"],
                      "schema_version": "verification-result-v2", "check_set_hash": job["check_set_hash"],
                      "domain_identity": job["domain_identity"], "environment": environment, "observation_refs": reports,
                      "measurement_scope": evidence.scope([s for s in measured_scope if s["subject_role"] == "candidate"]),
                      "baseline_comparison": evidence.compare(measured_scope, job, run),
                      "acceptance_binding_hash": job.get("acceptance_binding_hash"), "finished_at": time.time()}
            from .develop_cases import requirement_report
            result.update(case_observation_refs=case_reports,
                          requirement_observations=requirement_report(run["contract"], check_items, case_items))
            if result["requirement_observations"] is not None:
                result["requirement_observations"]["scope"] = {"run_id": run["run_id"], "job_id": job_id, "candidate_hash": job["candidate_hash"],
                            "check_set_hash": job["check_set_hash"], "contract_hash": job["contract_hash"], "acceptance_binding_hash": job.get("acceptance_binding_hash")}
            result["result_hash"] = canonical_hash(result)
    finally:
        done.set()
        monitor.join(timeout=2)
    with store.transaction() as connection:
        current = store.job(connection, job_id)
        active = store.run(connection, job["run_id"])
        if current.get("owner") != owner:
            return
        current["cleanup"] = "complete"
        current["heartbeat_at"] = time.time()
        valid = (current["status"] == "running" and active["status"] == "active" and active["active_job"] == job_id
                 and active["generation"] == job["generation"] and time.time() < job["deadline_at"] and not abort.is_set())
        if valid:
            current.update(status="error" if failure else "completed", result=result, error=failure)
            active.update(active_job=None, phase="review", verification={"status": "error" if failure else result["status"],
                          "job_id": job_id, "result_hash": result["result_hash"] if result else None, "check_set_hash": job["check_set_hash"],
                          "measurement_scope": evidence.scope([s for s in measured_scope if s["subject_role"] == "candidate"]),
                          "baseline_comparison": evidence.compare(measured_scope, job, run)})
            store.save_run(connection, active)
        elif current["status"] == "running":
            current.update(status="interrupted", error={"code": "LATE_RESULT_DISCARDED", "message": "Result arrived after ownership or deadline changed"})
            if failure:
                current["error"]["cause"] = failure
            if active["active_job"] == job_id:
                active.update(active_job=None, phase="review", verification={"status": "interrupted", "job_id": job_id})
                store.save_run(connection, active)
        store.save_job(connection, current)


def main():
    if len(sys.argv) != 3:
        raise SystemExit(2)
    execute_job(sys.argv[1], sys.argv[2])
