"""Detached, lease-bound verifier worker. Never calls a model or edits a workspace."""
from __future__ import annotations

import os
from pathlib import Path
import platform
import shutil
import signal
import subprocess
import sys
import threading
import time
import uuid

from harness.measurement_v5 import MeasurementEngine, decode
from harness.common import canonical_bytes, canonical_hash, redact
from .errors import HarnessError, require
from .snapshots import validate_candidate
from .store import Store, identifier
from . import semantics


def clean_environment() -> dict:
    # No provider credentials, Python module search overrides or application plugins.
    keys = ("PATH", "Path", "PATHEXT", "SystemRoot", "WINDIR", "TEMP", "TMP", "LANG", "LC_ALL", "BUN")
    return {key: os.environ[key] for key in keys if key in os.environ}


def spawn_worker(state_dir: Path, job_id: str) -> int:
    source = str(Path(__file__).resolve().parents[1])
    code = f"import sys; sys.path.insert(0, {source!r}); from harness_external.worker import main; main()"
    options = {"start_new_session": True} if os.name != "nt" else {"creationflags": subprocess.CREATE_NEW_PROCESS_GROUP}
    child = subprocess.Popen([sys.executable, "-I", "-c", code, str(state_dir), job_id], cwd=source,
                             stdin=subprocess.DEVNULL, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
                             env=clean_environment(), **options)
    return child.pid


def stop_child(child: subprocess.Popen) -> None:
    if os.name == "nt":
        if child.poll() is None:
            try:
                subprocess.run(["taskkill", "/PID", str(child.pid), "/T", "/F"], capture_output=True, timeout=5)
            except (OSError, subprocess.TimeoutExpired):
                child.kill()
    else:
        try:
            os.killpg(child.pid, signal.SIGTERM)
        except ProcessLookupError:
            pass
    try:
        child.wait(timeout=3)
    except subprocess.TimeoutExpired:
        if os.name == "nt":
            child.kill()
        else:
            try:
                os.killpg(child.pid, signal.SIGKILL)
            except ProcessLookupError:
                pass
        child.wait(timeout=3)


def execute_sandbox(check: dict, payload: Path, state_dir: Path, abort: threading.Event, remaining: float) -> dict:
    """Return only a receipt generated by our adapter, never one supplied by a caller."""
    started = time.time()
    bridge = Path(__file__).resolve().parents[2] / "runtime" / "script" / "external-harness-sandbox.ts"
    bun = shutil.which(os.environ.get("BUN", "bun"))
    if not bridge.is_file() or not bun:
        return {"status": "not_run", "reason": "SANDBOX_ADAPTER_UNAVAILABLE: source checkout and Bun are required for command checks"}
    require(not abort.is_set() and remaining > 0, "VERIFICATION_CANCELLED", "Verification was cancelled")
    request = {"workspace": str(payload), "argv": check["argv"], "cwd": check["cwd"],
               "timeoutMs": max(1, min(int(remaining * 1000), check["timeout_seconds"] * 1000))}
    environment = clean_environment()
    environment["XDG_STATE_HOME"] = str(state_dir / "sandbox-state")
    options = {"start_new_session": True} if os.name != "nt" else {"creationflags": subprocess.CREATE_NEW_PROCESS_GROUP}
    child = subprocess.Popen([bun, "run", str(bridge)], cwd=bridge.parent,
                             stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE,
                             env=environment, **options)
    try:
        first = True
        # The existing sandbox adapter caps process streams; this outer deadline
        # bounds setup, cleanup, and a stuck adapter as well.
        while True:
            if abort.is_set() or time.time() - started > remaining:
                stop_child(child)
                raise HarnessError("VERIFICATION_CANCELLED", "Verification cancelled or job deadline expired")
            try:
                output, errors = child.communicate(canonical_bytes(request) if first else None, timeout=0.2)
                break
            except subprocess.TimeoutExpired:
                first = False
        require(len(output) <= 1024 * 1024 and child.returncode == 0, "SANDBOX_ADAPTER_ERROR", "Sandbox adapter failed or exceeded protocol bounds")
        value = decode(output.decode("utf-8"))
        require(isinstance(value, dict) and value.get("status") in {"completed", "not_run", "error"}, "SANDBOX_PROTOCOL", "Invalid sandbox adapter response")
        return value
    finally:
        if child.poll() is None:
            stop_child(child)
        for stream in (child.stdin, child.stdout, child.stderr):
            if stream:
                stream.close()


def execute_job(state_dir: str | Path, job_id: str) -> None:
    from .service import verifier_identity
    store = Store(state_dir)
    owner = uuid.uuid4().hex
    abort, done = threading.Event(), threading.Event()
    with store.transaction() as connection:
        job = store.job(connection, job_id)
        run = store.run(connection, job["run_id"])
        if job["status"] != "queued" or run["active_job"] != job_id or run["status"] != "active":
            return
        job.update(status="running", heartbeat_at=time.time(), owner=owner, pid=os.getpid(), cleanup="running")
        store.save_job(connection, job)
        run["verification"] = {"status": "running", "job_id": job_id}
        store.save_run(connection, run)

    def heartbeat():
        while not done.wait(1):
            try:
                with store.transaction() as connection:
                    current = store.job(connection, job_id)
                    active = store.run(connection, job["run_id"])
                    if current["status"] != "running" or current.get("owner") != owner or active["status"] != "active" or active["active_job"] != job_id or time.time() >= job["deadline_at"]:
                        abort.set()
                        return
                    current["heartbeat_at"] = time.time()
                    store.save_job(connection, current)
            except Exception:
                abort.set()
                return

    monitor = threading.Thread(target=heartbeat, daemon=True)
    monitor.start()
    result = None
    failure = None
    reports = []
    comparisons = []
    environment = {}
    try:
        require(time.time() < job["deadline_at"], "DEADLINE_EXCEEDED", "Job expired before execution")
        require(run["contract"]["verifier"] == verifier_identity(), "VERIFIER_CHANGED", "Pinned verifier implementation changed")
        require(job.get("check_set_hash") == semantics.check_set_hash(job["checks"]), "CHECK_SET_CHANGED", "Pinned check set changed")
        candidate = job["candidate"]
        payload = store.directory(run["run_id"]) / identifier(candidate["candidate_id"], "candidate") / "payload"
        validate_candidate(candidate, payload)
        environment = {"python": platform.python_version(), "platform": platform.platform(),
                       "verifier": run["contract"]["verifier"]["implementation_hash"], "assurance": "local-advisory"}
        engine = MeasurementEngine()
        def envelope(kind, request_id, body):
            return {"version": 5, "id": request_id, "runId": run["run_id"], "scopeId": job_id, "type": kind, "payload": body}
        engine.handle(envelope("run.open", "open-" + job_id, {"snapshotRoot": str(payload)}))
        for index, check_record in enumerate(job["checks"]):
            spec = dict(check_record["spec"])
            check = dict(spec["parameters"])
            require(not abort.is_set() and time.time() < job["deadline_at"], "VERIFICATION_CANCELLED", "Worker no longer owns the verification")
            validate_candidate(candidate, payload)
            measurement = {"subject": candidate["subject"], "manifestJson": canonical_bytes(candidate["manifest"]).decode(),
                           "environmentHash": canonical_hash(environment)}
            provenance = None
            if check["kind"] == "command":
                check["timeout_seconds"] = max(1, spec["timeoutMs"] // 1000)
                capture = execute_sandbox(check, payload, store.root, abort, job["deadline_at"] - time.time())
                parameters = {"kind": "command", "argv": check["argv"], "cwd": check["cwd"], "expectedExitCode": 0}
                if capture["status"] in {"completed", "error"} and capture.get("capture"):
                    receipt = capture["capture"]
                    require(receipt["argv"] == check["argv"] and receipt["cwd"] == check["cwd"], "RECEIPT_BINDING", "Command receipt identity mismatch")
                    measurement["capture"] = {**receipt, "stdout": redact(receipt["stdout"]), "stderr": redact(receipt["stderr"])}
                    provenance = capture.get("provenance")
                else:
                    provenance = capture
                capabilities, timeout = ["execute"], check["timeout_seconds"] * 1000
            else:
                parameters, capabilities, timeout = check, ["read"], 1000
            spec = {**spec, "parameters": parameters, "ref": check_record["ref"]}
            measurement["check"] = spec
            report = engine.handle(envelope("measure", job_id + ":" + str(index), measurement))
            item = {"check_index": index, "observation": redact(report), "sandbox": provenance}
            checkpoint = {"observation_id": report["observationId"], "run_id": run["run_id"], "job_id": job_id,
                          "attempt": run["verification_attempts"], "check_id": check_record["check_id"], "check_ref": check_record["ref"],
                          "subject": candidate["subject"], "candidate_hash": candidate["candidate_hash"], "contract_hash": job["contract_hash"],
                          "interpretation_ref": job["interpretation_ref"], "policy_ref": job["policy_ref"],
                          "check_set_hash": job["check_set_hash"], "domain_identity": job["domain_identity"],
                          "comparison_status": semantics.comparison_status(report), "origin": "verifier", "trust": "locally_measured",
                          "report": item}
            checkpoint["record_hash"] = canonical_hash(checkpoint)
            with store.transaction() as connection:
                store.checkpoint(connection, job_id, owner, checkpoint)
            reports.append({"observation_id": checkpoint["observation_id"], "record_hash": checkpoint["record_hash"]})
            comparisons.append(checkpoint["comparison_status"])
        validate_candidate(candidate, payload)
        status = "passed" if all(s == "passed" for s in comparisons) else "failed"
        if "incomplete" in comparisons:
            status = "incomplete"
        result = {"status": status, "candidate_hash": job["candidate_hash"], "contract_hash": job["contract_hash"],
                  "schema_version": "verification-result-v2", "check_set_hash": job["check_set_hash"],
                  "domain_identity": job["domain_identity"], "environment": environment, "observation_refs": reports, "finished_at": time.time()}
        result["result_hash"] = canonical_hash(result)
    except Exception as error:
        failure = {"code": getattr(error, "code", "VERIFICATION_ERROR"), "message": str(redact(str(error)))[:2000]}
        if reports:
            result = {"status": "incomplete", "candidate_hash": job["candidate_hash"], "contract_hash": job["contract_hash"],
                      "schema_version": "verification-result-v2", "check_set_hash": job["check_set_hash"],
                      "domain_identity": job["domain_identity"], "environment": environment, "observation_refs": reports, "finished_at": time.time()}
            result["result_hash"] = canonical_hash(result)
    finally:
        done.set()
        monitor.join(timeout=2)
    with store.transaction() as connection:
        current = store.job(connection, job_id)
        active = store.run(connection, job["run_id"])
        if current.get("owner") != owner:
            return
        current["cleanup"] = "complete"
        current["heartbeat_at"] = time.time()
        valid = (current["status"] == "running" and active["status"] == "active" and active["active_job"] == job_id
                 and active["generation"] == job["generation"] and time.time() < job["deadline_at"] and not abort.is_set())
        if valid:
            current.update(status="error" if failure else "completed", result=result, error=failure)
            active.update(active_job=None, phase="review", verification={"status": "error" if failure else result["status"],
                          "job_id": job_id, "result_hash": result["result_hash"] if result else None, "check_set_hash": job["check_set_hash"]})
            store.save_run(connection, active)
        elif current["status"] == "running":
            current.update(status="interrupted", error={"code": "LATE_RESULT_DISCARDED", "message": "Result arrived after ownership or deadline changed"})
            if active["active_job"] == job_id:
                active.update(active_job=None, phase="review", verification={"status": "interrupted", "job_id": job_id})
                store.save_run(connection, active)
        store.save_job(connection, current)


def main():
    if len(sys.argv) != 3:
        raise SystemExit(2)
    execute_job(sys.argv[1], sys.argv[2])
